"""initial tables

Revision ID: 0d2f66ccf64c
Revises: 
Create Date: 2026-04-16 17:50:40.726143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d2f66ccf64c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False, comment='全局唯一 ID，用于外部暴露'),
    sa.Column('dingtalk_userid', sa.String(length=128), nullable=False, comment='钉钉用户唯一 ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='用户姓名'),
    sa.Column('role', sa.Enum('SALE', 'MANAGER', name='user_role', native_enum=False), nullable=False, comment='角色：SALE=销售，MANAGER=主管'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dingtalk_userid', name='uq_users_dingtalk_userid'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_users_dingtalk_userid'), 'users', ['dingtalk_userid'], unique=True)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False, comment='全局唯一 ID，用于外部暴露'),
    sa.Column('name', sa.String(length=256), nullable=False, comment="分身名称，如'价格异议客户'"),
    sa.Column('scenario_desc', sa.Text(), nullable=False, comment='场景描述，展示给销售看的简短说明'),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='核心字段：LLM System Prompt，定义 AI 分身的行为'),
    sa.Column('created_by_manager_id', sa.Integer(), nullable=True, comment='创建该分身的主管用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['created_by_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_personas_created_by_manager_id'), 'personas', ['created_by_manager_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False, comment='全局唯一 ID，用于外部暴露'),
    sa.Column('sale_user_id', sa.Integer(), nullable=False, comment='参与对练的销售用户 ID'),
    sa.Column('persona_id', sa.Integer(), nullable=True, comment='对练使用的 AI 分身 ID'),
    sa.Column('status', sa.Integer(), nullable=False, comment='会话状态：0=进行中，1=已完成，2=中断'),
    sa.Column('total_score', sa.Integer(), nullable=True, comment='综合评分（0-100），会话结束后填写'),
    sa.Column('score_detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="分维度评分详情 JSON，如 {'沟通技巧': 85, '产品知识': 72}"),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='综合报告 JSON，含扣分点、改进建议等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_sessions_persona_id'), 'sessions', ['persona_id'], unique=False)
    op.create_index(op.f('ix_sessions_sale_user_id'), 'sessions', ['sale_user_id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False, comment='全局唯一 ID，用于外部暴露'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属对练会话 ID'),
    sa.Column('role', sa.String(length=32), nullable=False, comment='消息发送方：SALE=销售，AI=AI分身'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息文本内容'),
    sa.Column('audio_url', sa.String(length=512), nullable=True, comment='TTS 生成的音频 URL（AI 回复时有值）'),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='元数据 JSON，如 ASR 置信度、LLM 响应时间等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_sale_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_persona_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_personas_created_by_manager_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_users_dingtalk_userid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
